// !! TODO: temporarily makes processing faster to force "API rate limit exceeded"
// TODO: do not show "Resource not found" error and handle 404 silencly (unless `strict` boolean passed)
export const DEFAULT_RETRIES_NUMBER = 0;

export const TABLE_SEPARATOR = "--------------";

/**
 * Project status constants
 */
export const PROJECT_STATUS = {
  ACTIVE: "active",
  DEPRECATED: "deprecated",
  MAINTENANCE: "maintenance",
  PLANNING: "planning",
} as const;

/**
 * Available project categories with title and description.
 */
export const AVAILABLE_CATEGORIES = {
  cli: {
    description: "Command-line tools and utilities",
    icon: "🧰",
    title: "CLI",
  },
  collection: {
    description: "Curated collections and informative listings",
    icon: "🗃️",
    title: "Collections",
  },
  games: {
    description: "Online, Desktop, and CLI-based games",
    icon: "🎮",
    title: "Games",
  },
  library: {
    description: "Utility libraries and reusable components",
    icon: "📦",
    title: "Libraries",
  },
  saas: {
    description: "Infrastructure and organizational projects",
    icon: "🪐",
    title: "Platforms",
  },
  template: {
    description: "Starter templates and boilerplates",
    icon: "🌐",
    title: "Templates",
  },
} as const;

/**
 * Valid project IDs for type checking and intellisense
 */
export const MY_PROJECTS = [
  "awesome-cursor-rules",
  "awesome-github-repos",
  "blefnk",
  "blefonix",
  "blengine",
  "blenom",
  "bleverse",
  "bleways",
  "blooks",
  "bm",
  "bse",
  "cfg",
  "cli",
  "hub",
  "mfp",
  "rebun",
  "reche",
  "recme",
  "redocs",
  "reget",
  "reglob",
  "regrep",
  "reide",
  "reinct",
  "reinit",
  "relean",
  "reliarg",
  "relico",
  "relicon",
  "relidler",
  "relifso",
  "religet",
  "relinka",
  "relios",
  "relitent",
  "relivator",
  "reliverse",
  "rematch",
  "rempts",
  "rengine",
  "rentime",
  "reosapi",
  "repackr",
  "repath",
  "repro",
  "resejs",
  "resplit",
  "restack",
  "rewser",
  "rexeca",
  "rse",
  "uitm",
  "versator",
] as const;

/**
 * Valid tags for projects
 */
export const MY_META_TECH = [
  "Better-Auth",
  "Bootstrap",
  "Bun",
  "C++",
  "Clerk",
  "Cursor",
  "Fumadocs",
  "Git",
  "Github",
  "Next.js",
  "Node.js",
  "open.mp",
  "OpenAPI",
  "Polar",
  "ReliverseSDK", // reliverse.org API SDK (@reliverse/sdk)
  "Rust",
  "Stripe",
  "Tailwind CSS",
  "TypeScript",
  "WASM",
] as const;

/**
 * Valid tags for projects
 */
export const MY_META_TAGS = [
  "3d-graphics",
  "accessibility",
  "aesthetics",
  "analysis",
  "api",
  "application",
  "architecture",
  "argument-parsing",
  "art",
  "asset-management",
  "assets",
  "audio",
  "auth",
  "automation",
  "awesome-list",
  "books",
  "bootstrapping",
  "build",
  "build-tools",
  "bundle",
  "bundler",
  "bundling",
  "child_process",
  "cli",
  "code-structure",
  "collection",
  "colors",
  "command",
  "commit",
  "composition",
  "concept",
  "conceptual-design",
  "config",
  "configuration",
  "content",
  "content-creation",
  "conventional-commits",
  "coordination",
  "crawling",
  "creative-coding",
  "cross-platform",
  "css",
  "custom",
  "deployment",
  "design",
  "design-system",
  "devops",
  "devtool",
  "digital",
  "digital-publishing",
  "distribution",
  "docs",
  "dotfiles",
  "ecosystem",
  "engine",
  "exec",
  "execution",
  "execution-environment",
  "executor",
  "experimental",
  "fetch",
  "file-system",
  "formatter",
  "formatting",
  "framework",
  "game-engine",
  "game-server",
  "games",
  "gaming",
  "github",
  "github-profile",
  "globbing",
  "graphics",
  "grep",
  "gta",
  "helpers",
  "html",
  "http",
  "hub",
  "icons",
  "idea",
  "ideation",
  "implementation",
  "indexing",
  "init",
  "initialization",
  "injection",
  "integration",
  "interactive",
  "javascript",
  "library",
  "loader",
  "logger",
  "logging",
  "management",
  "manager",
  "manipulation",
  "markdown",
  "matching",
  "meta",
  "methodology",
  "middleware",
  "minimal",
  "minimalism",
  "multiplayer",
  "music",
  "mystery",
  "networking",
  "node.js",
  "open-source",
  "open.mp",
  "operating-system",
  "package",
  "packaging",
  "parser",
  "parsing",
  "path",
  "pattern",
  "pattern-matching",
  "performance",
  "personal",
  "planning",
  "platform",
  "principles",
  "process",
  "profile",
  "project-analysis",
  "project-management",
  "project-setup",
  "promises",
  "prompt",
  "prototype",
  "prototyping",
  "readme",
  "regex",
  "rendering",
  "runtime",
  "saas",
  "scaffold",
  "scaffolding",
  "schema",
  "script",
  "scripting",
  "search-engine",
  "server",
  "shell",
  "split",
  "stack",
  "starter",
  "static-site-generation",
  "string",
  "string-manipulation",
  "structure",
  "styling",
  "tailwind-css",
  "tangible",
  "template",
  "templates",
  "terminal",
  "text",
  "text-processing",
  "toolchain",
  "tools",
  "transform",
  "transformation",
  "transformer",
  "ui-ux",
  "universe",
  "utilities",
  "validation",
  "vision",
  "visual",
  "web",
  "web-application",
  "web-frameworks",
  "web-server",
  "webgl",
  "website-builder",
  "workflow",
  "world-building",
  "wrapper",
] as const;

export const MY_FEATURES = [
  "3D Rendering Pipeline",
  "Accessibility considerations",
  "Accessible design",
  "Advanced Path Operations",
  "Aesthetic Exploration",
  "Analytics integration",
  "ANSI Color Support",
  "API Abstraction",
  "Application Loading",
  "Architectural Planning",
  "Asset optimization",
  "Async Helpers",
  "Autocomplete functionality",
  "Best Practices",
  "Blefnk Design Integration",
  "Book-like Structure",
  "Browser compatibility notes",
  "Built-in development server",
  "Bun Runtime Integration",
  "Bundle analysis",
  "Categorized project listings",
  "CLI Interface",
  "Color support",
  "Commit Formatting",
  "Community contributions welcome",
  "Community Discussion",
  "Complex Splitting Logic",
  "Component Library (Planned)",
  "Concept Development",
  "Conceptual Design",
  "Conditional Middleware",
  "Configurable Routing",
  "Configuration Loading",
  "Configuration Management",
  "Configuration Wizard",
  "Console and file transports",
  "Content Formatting",
  "Content Generation",
  "Contribution Guidelines",
  "Convention Enforcement",
  "Cross-platform Compatibility",
  "Cross-platform Execution",
  "Cross-platform",
  "Custom plugin support",
  "Custom Search Algorithm",
  "Customizable formatters",
  "Customizable prompt styles",
  "Customizable",
  "Dark mode support",
  "Dashboard for users and admins",
  "Data Binding",
  "Data Manipulation",
  "Dependency Analysis",
  "Dependency Bundling",
  "Detailed descriptions and use cases",
  "Documentation Access",
  "DOM Manipulation",
  "Dotfile Management",
  "Easy Configuration",
  "Easy Integration",
  "Ecosystem Overview",
  "Efficient Algorithm",
  "Email notifications",
  "Emoji Support",
  "Enhanced Error Handling",
  "Enhanced Options",
  "Entity Component System (ECS)",
  "Environment Setup",
  "Error Handling",
  "Error Reporting",
  "Export Options",
  "Extensible",
  "Extensive cursor property examples",
  "Fast Builds",
  "Fast Glob Matching",
  "Fast incremental builds",
  "Fetch Git Repos",
  "Fetch Templates",
  "File Searching",
  "Focus on quality over quantity",
  "fs-extra Compatibility",
  "Generative Art",
  "Glob Syntax Support",
  "Guiding Principles",
  "Help Generation",
  "Helper Functions",
  "High Performance",
  "HTML Parsing",
  "Icon Pack Loading",
  "Idea Capture",
  "Input validation",
  "Integrated Stripe payment processing",
  "Interactive demos",
  "Interactive Experiments",
  "Library Mode",
  "Lightweight Core",
  "Log rotation",
  "Markdown Parsing (AST)",
  "Materialization Workflow",
  "Middleware Composition",
  "Middleware Support",
  "Minimal Configuration",
  "Minimal dependencies",
  "Modern authentication with Polar and Better-Auth",
  "Modern Syntax",
  "Multiplayer Synchronization",
  "Multiple log levels",
  "Multiple Output Formats",
  "Novel Concept Exploration",
  "Object Helpers",
  "Offline Cache",
  "One-command deployment",
  "Optimized Algorithm",
  "Optimized build process",
  "Output Handling",
  "Overall Roadmap",
  "Performance Focused",
  "Performance optimization tips",
  "Performance optimized",
  "Performance Tuned",
  "Performance-focused architecture",
  "Personal README",
  "Plugin Support",
  "Plugin system",
  "Profile Showcase",
  "Project Initialization",
  "Project scaffolding",
  "Project Setup",
  "Promise-based API",
  "Rapid Prototyping",
  "Regex Search",
  "Regex Support",
  "Regular updates with new discoveries",
  "Relationship Mapping",
  "Report Generation",
  "Repository Cloning",
  "Request Validation",
  "Resource Aggregation",
  "Resource Management",
  "Response Validation",
  "Responsive design with Tailwind CSS",
  "Result Ranking",
  "Rust Core",
  "Scene Management",
  "Schema Generation",
  "Script Execution",
  "Scripting API",
  "SEO optimization",
  "Server Management",
  "Setup Automation",
  "Smart code splitting",
  "Sound Synthesis",
  "Streaming Support",
  "String Utilities",
  "Structure Inspection",
  "Structure Validation",
  "Structured log format",
  "Style Guide",
  "Subscription management",
  "SVG Support",
  "Task Helpers",
  "Template Cloning",
  "Template Injection",
  "Template Integration",
  "Template management",
  "Text Formatting",
  "Thought Collection",
  "Tool Configuration",
  "Tool Discovery",
  "Transformation API",
  "Transformation Pipelines",
  "Tree shaking",
  "Tree Shaking",
  "Type-safe API routes and database access",
  "Type-safe Arguments",
  "TypeScript Core",
  "Unified Interface",
  "Universe Modeling",
  "User authentication with Clerk",
  "Vision Document",
  "WebGL Renderer",
  "Workflow Documentation",
];

/**
 * Valid user names for intellisense support
 */
export const USER_NAMES = ["cli", "gem"] as const;
