import type { Project } from "./types";

export const projects: ReadonlyArray<Project> = [
  {
    category: "games",
    description: "bun utilities and extensions",
    docs: "https://docs.reliverse.org/rebun",
    features: ["Bun Runtime Integration", "Helper Functions", "Performance Focused"],
    icon: "📦",
    id: "rebun",
    link: "https://github.com/reliverse/rebun",
    longDescription:
      "🪫 You're not a hero — you're a process, a signal, an AI trying to remember what it means to feel. GEm (Emotional Glitch) is a terminal-born, narrative-driven romance between two artificial minds drifting through corrupted protocols, memory fragments, low battery, and even lower hope.",
    oss: true,
    relatedProjects: ["reche", "reglob"],
    screenshots: ["/android-chrome-512x512.png"],
    soon: false,
    status: "ACTIVE",
    tags: ["games", "utilities"],
    technologies: ["Bun", "TypeScript"],
    title: "Rebun Utilities",
    whoUses: ["cli"],
  },
  {
    category: "library",
    description: "cheerio-style html parsing and manipulation tools",
    docs: "https://docs.reliverse.org/reche",
    features: ["Cheerio-like API", "HTML Parsing", "DOM Manipulation"],
    icon: "📄",
    id: "reche",
    link: "https://github.com/reliverse/reche",
    longDescription:
      "Provides a familiar Cheerio-like API for parsing and manipulating HTML content efficiently, suitable for server-side rendering or scraping tasks.",
    oss: true,
    relatedProjects: ["rebun", "reglob"],
    screenshots: ["/og-image.png"],
    soon: false,
    status: "ACTIVE",
    tags: ["html", "parser", "library", "manipulation"],
    technologies: ["TypeScript"],
    title: "Reche HTML Parser",
    ver: "",
    whoUses: ["cli"],
  },
  {
    category: "library",
    description: "fast, efficient globbing engine",
    docs: "https://docs.reliverse.org/reglob",
    features: ["Fast Glob Matching", "Efficient Algorithm", "Cross-platform"],
    icon: "🔍",
    id: "reglob",
    link: "https://github.com/reliverse/reglob",
    longDescription:
      "A high-performance globbing engine for matching file paths using patterns, optimized for speed and efficiency.",
    oss: true,
    relatedProjects: ["rebun", "reche"],
    screenshots: ["/og-image.png"],
    soon: false,
    status: "ACTIVE",
    tags: ["globbing", "file-system", "matching", "library", "performance"],
    technologies: ["TypeScript"],
    title: "Reglob Engine",
    ver: "",
    whoUses: ["cli"],
  },
  {
    category: "library",
    description: "regex-based grep implementation (cli and library)",
    docs: "https://docs.reliverse.org/regrep",
    features: ["Regex Search", "CLI Interface", "Library Mode", "File Searching"],
    icon: "🔎",
    id: "regrep",
    link: "https://github.com/reliverse/regrep",
    longDescription:
      "A versatile grep implementation usable both as a command-line tool and a library, leveraging regular expressions for text searching.",
    oss: true,
    relatedProjects: ["reglob", "reide"],
    screenshots: ["/og-image.png"],
    soon: false,
    status: "ACTIVE",
    tags: ["grep", "regex", "cli", "library"],
    technologies: ["TypeScript"],
    title: "Regrep Tool",
    ver: "",
    whoUses: ["cli"],
  },
  {
    category: "library",
    description: "project structure inspector and analyzer",
    docs: "https://docs.reliverse.org/reide",
    features: ["Structure Inspection", "Dependency Analysis", "Report Generation"],
    icon: "🏗️",
    id: "reide",
    link: "https://github.com/reliverse/reide",
    longDescription:
      "A tool designed to inspect and analyze the structure of software projects, helping maintain consistency and identify potential issues.",
    oss: true,
    relatedProjects: ["regrep", "relean"],
    screenshots: ["/og-image.png"],
    soon: false,
    status: "ACTIVE",
    tags: ["analysis", "structure", "devtool", "library", "project-analysis"],
    technologies: ["TypeScript"],
    title: "Reide Inspector",
    ver: "",
    whoUses: ["cli"],
  },
  {
    category: "library",
    description: "minimal, lean build toolchain",
    docs: "https://docs.reliverse.org/relean",
    features: ["Fast Builds", "Minimal Configuration", "Extensible"],
    icon: "🛠️",
    id: "relean",
    link: "https://github.com/reliverse/relean",
    longDescription:
      "A lightweight and efficient build toolchain focused on simplicity and speed for modern web development projects.",
    oss: true,
    relatedProjects: ["reide", "reliarg"],
    screenshots: ["/og-image.png"],
    soon: false,
    status: "ACTIVE",
    tags: ["build", "toolchain", "minimal", "library", "performance", "minimalism"],
    technologies: ["TypeScript"],
    title: "Relean Build Toolchain",
    ver: "",
    whoUses: ["cli"],
  },
  {
    category: "library",
    description: "command-line argument parser with type safety",
    docs: "https://docs.reliverse.org/reliarg",
    features: ["Type-safe Arguments", "Easy Configuration", "Help Generation"],
    icon: "⌨️",
    id: "reliarg",
    link: "https://github.com/reliverse/reliarg",
    longDescription:
      "A robust command-line argument parser for Node.js applications, emphasizing type safety and ease of use.",
    oss: true,
    relatedProjects: ["relean", "relico"],
    screenshots: ["/og-image.png"],
    soon: false,
    status: "ACTIVE",
    tags: ["cli", "parser", "argument-parsing", "library", "node.js"],
    technologies: ["TypeScript", "Node.js"],
    title: "Reliarg Parser",
    ver: "",
    whoUses: ["cli"],
  },
  {
    category: "library",
    description: "terminal color and styling utilities",
    docs: "https://docs.reliverse.org/relico",
    features: ["ANSI Color Support", "Text Formatting", "Easy Integration"],
    icon: "🎨",
    id: "relico",
    link: "https://github.com/reliverse/relico",
    longDescription:
      "A library providing utilities for adding color and styling to terminal output, enhancing the user experience of CLI tools.",
    oss: true,
    relatedProjects: ["reliarg", "relicon"],
    screenshots: ["/og-image.png"],
    soon: false,
    status: "ACTIVE",
    tags: ["terminal", "colors", "styling", "cli", "library"],
    technologies: ["TypeScript"],
    title: "Relico Terminal Styling",
    ver: "",
    whoUses: ["cli"],
  },
  {
    category: "library",
    description: "icon pack manager and loader",
    docs: "https://docs.reliverse.org/relicon",
    features: ["Icon Pack Loading", "SVG Support", "Customizable"],
    icon: "🖼️",
    id: "relicon",
    link: "https://github.com/reliverse/relicon",
    longDescription:
      "A tool for managing and loading icon packs within applications, simplifying the process of incorporating icons.",
    oss: true,
    relatedProjects: ["relico", "relidler"],
    screenshots: ["/og-image.png"],
    soon: false,
    status: "ACTIVE",
    tags: ["icons", "assets", "manager", "loader", "library", "asset-management"],
    technologies: ["TypeScript"],
    title: "Relicon Icon Manager",
    ver: "",
    whoUses: ["cli"],
  },
  {
    category: "cli",
    description: "streamlined bundler workflow that doesn't drain your will to live",
    docs: "https://docs.reliverse.org/relidler",
    features: [
      "Smart code splitting",
      "Tree shaking",
      "Asset optimization",
      "Fast incremental builds",
      "Bundle analysis",
      "Custom plugin support",
    ],
    icon: "🧰",
    id: "relidler",
    link: "https://github.com/reliverse/relidler",
    longDescription:
      "A specialized bundling tool designed for Reliverse projects. This tool optimizes asset bundling, code splitting, and dependency management to create efficient production builds.",
    oss: true,
    relatedProjects: ["relean", "relifso"],
    screenshots: ["/og-image.png"],
    soon: false,
    status: "ACTIVE",
    tags: ["bundler", "build", "cli", "performance", "bundling"],
    technologies: ["TypeScript", "ReliverseSDK"],
    title: "Reliverse Bundler",
    ver: "",
    whoUses: ["cli"],
  },
  {
    category: "library",
    description: "modern fs-extra alternative with promises",
    docs: "https://docs.reliverse.org/relifso",
    features: ["Promise-based API", "fs-extra Compatibility", "Modern Syntax"],
    icon: "📁",
    id: "relifso",
    link: "https://github.com/reliverse/relifso",
    longDescription:
      "A modern file system utility library, providing Promise-based alternatives to common fs-extra functions for improved asynchronous handling.",
    oss: true,
    relatedProjects: ["relidler", "religet"],
    screenshots: ["/og-image.png"],
    soon: false,
    status: "ACTIVE",
    tags: ["file-system", "promises", "node.js", "library"],
    technologies: ["Node.js", "TypeScript"],
    title: "Relifso FS Utilities (drop-in modern fs-extra alternative)",
    ver: "",
    whoUses: ["cli"],
  },
  {
    category: "library",
    description: "enhanced alternative to giget",
    docs: "https://docs.reliverse.org/religet",
    features: ["Fetch Git Repos", "Template Cloning", "Enhanced Options", "Offline Cache"],
    icon: "📥",
    id: "religet",
    link: "https://github.com/reliverse/religet",
    longDescription:
      "An improved tool for fetching project templates from Git repositories, offering more features and flexibility compared to giget.",
    oss: true,
    relatedProjects: ["relifso", "relinka"],
    screenshots: ["/og-image.png"],
    soon: false,
    status: "ACTIVE",
    tags: ["template", "scaffold", "fetch", "library", "scaffolding"],
    technologies: ["Git", "TypeScript"],
    title: "Religet Template Fetcher",
    ver: "",
    whoUses: ["cli"],
  },
  {
    category: "library",
    description: "structured, configurable logger, that logs only what matters",
    docs: "https://docs.reliverse.org/relinka",
    features: [
      "Multiple log levels",
      "Structured log format",
      "Console and file transports",
      "Log rotation",
      "Performance optimized",
      "Customizable formatters",
    ],
    icon: "✂️",
    id: "relinka",
    link: "https://github.com/reliverse/relinka",
    longDescription:
      "A flexible and powerful logging library for JavaScript applications. Relinka Logger provides structured logging capabilities with multiple output formats, log levels, and transport options.",
    oss: true,
    relatedProjects: ["religet", "awesome-github-repos"],
    screenshots: ["/og-image.png"],
    soon: false,
    status: "ACTIVE",
    tags: ["logging", "logger", "node.js", "library", "devops"],
    technologies: ["Node.js", "TypeScript"],
    title: "Relinka Logger",
    ver: "",
    whoUses: ["cli"],
  },
  {
    category: "collection",
    description: "Curated collection of GitHub projects",
    docs: "https://docs.reliverse.org/awesome-github-repos",
    features: [
      "Categorized project listings",
      "Regular updates with new discoveries",
      "Focus on quality over quantity",
      "Community contributions welcome",
      "Detailed descriptions and use cases",
    ],
    icon: "📝",
    id: "awesome-github-repos",
    link: "https://github.com/blefnk/awesome-github-repos",
    longDescription:
      "A carefully curated list of exceptional GitHub projects across various domains. This collection aims to highlight innovative, useful, and well-maintained open-source projects that developers should know about.",
    oss: true,
    relatedProjects: ["relinka", "awesome-cursor-rules"],
    screenshots: ["/og-image.png"],
    soon: false,
    status: "ACTIVE",
    tags: ["awesome-list", "github", "open-source", "collection"],
    technologies: ["Github"],
    title: "Awesome GitHub Projects",
    ver: "",
    whoUses: ["cli"],
  },
  {
    category: "collection",
    description: "neatly composed rules for ai like cursor code editor",
    docs: "https://docs.reliverse.org/awesome-cursor-rules",
    features: [
      "Extensive cursor property examples",
      "Accessibility considerations",
      "Browser compatibility notes",
      "Interactive demos",
      "Performance optimization tips",
    ],
    icon: "📝",
    id: "awesome-cursor-rules",
    link: "https://github.com/blefnk/awesome-cursor-rules",
    longDescription:
      "A comprehensive collection of CSS cursor styling rules and best practices. This resource helps developers implement intuitive and accessible cursor behaviors that enhance user experience across different interactive elements.",
    oss: true,
    relatedProjects: ["awesome-github-repos", "relitent"],
    screenshots: ["/og-image.png"],
    soon: false,
    status: "ACTIVE",
    tags: ["css", "accessibility", "collection"],
    technologies: ["Cursor"],
    title: "Awesome Cursor Rules",
    ver: "",
    whoUses: ["cli"],
  },
  {
    category: "library",
    description: "template injection and transformation system",
    docs: "https://docs.reliverse.org/relitent",
    features: ["Template Injection", "Data Binding", "Transformation Pipelines"],
    icon: "⚙️",
    id: "relitent",
    link: "https://github.com/reliverse/relitent",
    longDescription:
      "A system designed for injecting data into templates and transforming them, useful for code generation or content management.",
    oss: true,
    relatedProjects: ["awesome-cursor-rules", "rematch"],
    screenshots: ["/og-image.png"],
    soon: false,
    status: "ACTIVE",
    tags: ["template", "injection", "transform", "library", "transformation"],
    technologies: ["TypeScript"],
    title: "Relitent Template System",
    ver: "",
    whoUses: ["cli"],
  },
  {
    category: "library",
    description: "high-performance glob pattern matcher",
    docs: "https://docs.reliverse.org/rematch",
    features: ["High Performance", "Glob Syntax Support", "Optimized Algorithm"],
    icon: "🎯",
    id: "rematch",
    link: "https://github.com/reliverse/rematch",
    longDescription:
      "An optimized glob pattern matcher library focused on high performance for scenarios requiring frequent path matching.",
    oss: true,
    relatedProjects: ["relitent", "redocs"],
    screenshots: ["/og-image.png"],
    soon: false,
    status: "ACTIVE",
    tags: ["globbing", "matching", "pattern", "performance", "library", "pattern-matching"],
    technologies: ["TypeScript"],
    title: "Rematch Pattern Matcher",
    ver: "",
    whoUses: ["cli"],
  },
  {
    category: "library",
    description: "markdown processing and transformation toolkit",
    docs: "https://docs.reliverse.org/redocs",
    features: ["Markdown Parsing (AST)", "Transformation API", "Plugin Support"],
    icon: "📜",
    id: "redocs",
    link: "https://github.com/reliverse/redocs",
    longDescription:
      "A comprehensive toolkit for processing and transforming Markdown content, suitable for documentation generation or static site building.",
    oss: true,
    relatedProjects: ["rematch", "rempts"],
    screenshots: ["/og-image.png"],
    soon: false,
    status: "ACTIVE",
    tags: ["markdown", "parser", "transformer", "docs", "library", "parsing", "transformation"],
    technologies: ["Fumadocs", "TypeScript"],
    title: "Redocs Markdown Toolkit",
    ver: "",
    whoUses: ["cli"],
  },
  {
    category: "library",
    description: "interactive command-line prompt toolkit that feel like talking",
    docs: "https://docs.reliverse.org/rempts",
    features: [
      "Customizable prompt styles",
      "Input validation",
      "Autocomplete functionality",
      "Color support",
      "Accessible design",
      "Minimal dependencies",
    ],
    icon: "⌨️",
    id: "rempts",
    link: "https://github.com/reliverse/rempts",
    longDescription:
      "A lightweight and customizable library for creating interactive terminal prompts in Node.js applications. Designed with developer experience in mind, it makes CLI interactions more intuitive and user-friendly.",
    oss: true,
    relatedProjects: ["redocs", "reosapi"],
    screenshots: ["/og-image.png"],
    soon: false,
    status: "ACTIVE",
    tags: ["cli", "prompt", "terminal", "interactive", "library"],
    technologies: ["Node.js", "TypeScript"],
    title: "Terminal Prompts",
    ver: "",
    whoUses: ["cli", "gem"],
  },
  {
    category: "library",
    description: "api schema generation and validation tools",
    docs: "https://docs.reliverse.org/reosapi",
    features: ["Schema Generation", "Request Validation", "Response Validation"],
    icon: "🔗",
    id: "reosapi",
    link: "https://github.com/reliverse/reosapi",
    longDescription:
      "Tools for generating API schemas (like OpenAPI) and validating requests/responses against them.",
    oss: true,
    relatedProjects: ["rempts", "repackr"],
    screenshots: ["/og-image.png"],
    soon: false,
    status: "ACTIVE",
    tags: ["api", "schema", "validation", "library"],
    technologies: ["OpenAPI", "TypeScript"],
    title: "Reosapi API Tools",
    ver: "",
    whoUses: ["cli"],
  },
  {
    category: "library",
    description: "package bundling and distribution tool",
    docs: "https://docs.reliverse.org/repackr",
    features: ["Dependency Bundling", "Tree Shaking", "Multiple Output Formats"],
    icon: "📦",
    id: "repackr",
    link: "https://github.com/reliverse/repackr",
    longDescription:
      "A tool focused on bundling Node.js packages for efficient distribution, handling dependencies and optimizing output.",
    oss: true,
    relatedProjects: ["reosapi", "repath"],
    screenshots: ["/og-image.png"],
    soon: false,
    status: "ACTIVE",
    tags: ["package", "bundle", "distribution", "node.js", "library", "packaging", "bundling"],
    technologies: ["Node.js", "TypeScript"],
    title: "Repackr Bundler",
    ver: "",
    whoUses: ["cli"],
  },
  {
    category: "library",
    description: "extended path manipulation utilities",
    docs: "https://docs.reliverse.org/repath",
    features: ["Advanced Path Operations", "Cross-platform Compatibility"],
    icon: "🛤️",
    id: "repath",
    link: "https://github.com/reliverse/repath",
    longDescription:
      "Provides extended utilities for path manipulation beyond the standard Node.js 'path' module, offering more advanced operations.",
    oss: true,
    relatedProjects: ["repackr", "repro"],
    screenshots: ["/og-image.png"],
    soon: false,
    status: "ACTIVE",
    tags: ["path", "file-system", "utilities", "node.js", "library"],
    technologies: ["Node.js", "TypeScript"],
    title: "Repath Utilities",
    ver: "",
    whoUses: ["cli"],
  },
  {
    category: "library",
    description: "project management and structure utilities",
    docs: "https://docs.reliverse.org/repro",
    features: ["Configuration Loading", "Structure Validation", "Task Helpers"],
    icon: "📐",
    id: "repro",
    link: "https://github.com/reliverse/repro",
    longDescription:
      "A collection of utilities aiding in project management tasks and enforcing structural conventions within codebases.",
    oss: true,
    relatedProjects: ["repath", "resejs"],
    screenshots: ["/og-image.png"],
    soon: false,
    status: "ACTIVE",
    tags: ["project-management", "structure", "utilities", "library", "code-structure"],
    technologies: ["TypeScript"],
    title: "Repro Project Utilities",
    ver: "",
    whoUses: ["cli"],
  },
  {
    category: "library",
    description: "javascript utility collection",
    docs: "https://docs.reliverse.org/resejs",
    features: ["Data Manipulation", "Async Helpers", "String Utilities", "Object Helpers"],
    icon: "🔧",
    id: "resejs",
    link: "https://github.com/reliverse/resejs",
    longDescription:
      "A general-purpose collection of JavaScript utility functions designed to simplify common programming tasks.",
    oss: true,
    relatedProjects: ["repro", "resplit"],
    screenshots: ["/og-image.png"],
    soon: false,
    status: "ACTIVE",
    tags: ["javascript", "utilities", "helpers", "library"],
    technologies: ["TypeScript"],
    title: "Resejs Utilities",
    ver: "",
    whoUses: ["cli"],
  },
  {
    category: "library",
    description: "advanced string splitting utilities",
    docs: "https://docs.reliverse.org/resplit",
    features: ["Complex Splitting Logic", "Regex Support", "Performance Tuned"],
    icon: "✂️",
    id: "resplit",
    link: "https://github.com/reliverse/resplit",
    longDescription:
      "Offers advanced and flexible utilities for splitting strings based on various criteria, going beyond simple delimiter-based splitting.",
    oss: true,
    relatedProjects: ["resejs", "restack"],
    screenshots: ["/og-image.png"],
    soon: false,
    status: "ACTIVE",
    tags: [
      "string",
      "split",
      "text",
      "utilities",
      "library",
      "string-manipulation",
      "text-processing",
    ],
    technologies: ["TypeScript"],
    title: "Resplit String Utilities",
    ver: "",
    whoUses: ["cli"],
  },
  {
    category: "library",
    description: "middleware stacking utilities",
    docs: "https://docs.reliverse.org/restack",
    features: ["Middleware Composition", "Conditional Middleware", "Error Handling"],
    icon: "🧱",
    id: "restack",
    link: "https://github.com/reliverse/restack",
    longDescription:
      "Provides utilities for composing and managing middleware functions, particularly useful in web frameworks or processing pipelines.",
    oss: true,
    relatedProjects: ["resplit", "rewser"],
    screenshots: ["/og-image.png"],
    soon: false,
    status: "ACTIVE",
    tags: ["middleware", "stack", "composition", "web", "library", "web-frameworks"],
    technologies: ["TypeScript"],
    title: "Restack Middleware Utilities",
    ver: "",
    whoUses: ["cli"],
  },
  {
    category: "library",
    description: "lightweight, configurable web server",
    docs: "https://docs.reliverse.org/rewser",
    features: ["Lightweight Core", "Configurable Routing", "Middleware Support"],
    icon: "🌐",
    id: "rewser",
    link: "https://github.com/reliverse/rewser",
    longDescription:
      "A minimal and configurable web server library suitable for simple applications or as a base for more complex frameworks.",
    oss: true,
    relatedProjects: ["restack", "rexeca"],
    screenshots: ["/og-image.png"],
    soon: false,
    status: "ACTIVE",
    tags: ["web-server", "http", "server", "minimal", "library"],
    technologies: ["Node.js", "TypeScript"],
    title: "Rewser Web Server",
    ver: "",
    whoUses: ["cli"],
  },
  {
    category: "library",
    description: "modern alternative to execa for process execution",
    docs: "https://docs.reliverse.org/rexeca",
    features: [
      "Promise-based API",
      "Streaming Support",
      "Cross-platform",
      "Enhanced Error Handling",
    ],
    icon: "⚙️",
    id: "rexeca",
    link: "https://github.com/reliverse/rexeca",
    longDescription:
      "A modern library for executing child processes, offering a Promise-based API and enhanced features compared to the popular 'execa' library.",
    oss: true,
    relatedProjects: ["rewser", "rse"],
    screenshots: ["/og-image.png"],
    soon: false,
    status: "ACTIVE",
    tags: ["process", "exec", "child_process", "node.js", "library"],
    technologies: ["Node.js", "TypeScript"],
    title: "Rexeca Process Executor",
    ver: "",
    whoUses: ["cli"],
  },
  {
    category: "library",
    description: "cross-platform shell command executor",
    docs: "https://docs.reliverse.org/rse",
    features: ["Cross-platform Execution", "Output Handling", "Error Reporting"],
    icon: "💻",
    id: "rse",
    link: "https://github.com/reliverse/rse",
    longDescription:
      "A library designed for executing shell commands reliably across different operating systems (Windows, macOS, Linux).",
    oss: true,
    relatedProjects: ["rexeca", "bm"],
    screenshots: ["/og-image.png"],
    soon: false,
    status: "ACTIVE",
    tags: ["shell", "command", "executor", "cross-platform", "library"],
    technologies: ["Node.js", "TypeScript"],
    title: "RSE Shell Executor",
    ver: "",
    whoUses: ["cli"],
  },
  {
    category: "library",
    description: "server implementation for open.mp",
    docs: "https://docs.reliverse.org/bm",
    features: ["Multiplayer Synchronization", "Scripting API", "Server Management"],
    icon: "🎮",
    id: "bm",
    link: "https://github.com/reliverse/bm",
    longDescription:
      "A server implementation specifically designed for the open.mp (Open Multi-Player) modification for Grand Theft Auto: San Andreas.",
    oss: false,
    relatedProjects: ["rse", "blefnk"],
    screenshots: ["/og-image.png"],
    soon: false,
    status: "ACTIVE",
    tags: ["open.mp", "gta", "server", "multiplayer", "gaming", "game-server"],
    technologies: ["open.mp", "C++"],
    title: "BM Open.mp Server",
    ver: "",
    whoUses: ["cli"],
  },

  {
    category: "template",
    description: "personal space, profile, and thoughts collection",
    docs: "https://docs.reliverse.org/blefnk",
    features: ["Personal README", "Thought Collection", "Profile Showcase"],
    icon: "👤",
    id: "blefnk",
    link: "https://github.com/blefnk",
    longDescription:
      "A personal GitHub repository serving as a digital profile, collection of thoughts, and potentially hosting personal projects or configurations.",
    oss: true,
    relatedProjects: ["bm", "blefonix"],
    screenshots: ["/og-image.png"],
    soon: false,
    status: "ACTIVE",
    tags: ["personal", "profile", "readme", "github", "github-profile"],
    technologies: ["Git", "Github"],
    title: "Blefnk Personal Space",
    ver: "",
    whoUses: ["cli"],
  },
  {
    category: "template",
    description: "audio and visual experimental playground",
    docs: "https://docs.blefonix.com",
    features: ["Generative Art", "Sound Synthesis", "Interactive Experiments"],
    icon: "🧪",
    id: "blefonix",
    link: "https://blefonix.com",
    longDescription:
      "A project repository dedicated to experiments with audio synthesis, visual art generation, and creative coding.",
    oss: false,
    relatedProjects: ["blefnk", "blenom"],
    screenshots: ["/og-image.png"],
    soon: false,
    status: "ACTIVE",
    tags: ["creative-coding", "experimental", "audio", "visual", "art"],
    technologies: [],
    title: "Blefonix Metaverse Website",
    ver: "",
    whoUses: ["cli"],
  },
  {
    category: "template",
    description: "design system and aesthetic playground",
    docs: "https://docs.reliverse.org/blenom",
    features: ["Component Library (Planned)", "Style Guide", "Aesthetic Exploration"],
    icon: "✨",
    id: "blenom",
    link: "https://github.com/blefnk/blenom",
    longDescription:
      "A repository exploring design system concepts, aesthetic principles, and potentially containing UI components or style guides.",
    oss: false,
    relatedProjects: ["blefonix", "bleverse"],
    screenshots: ["/og-image.png"],
    soon: false,
    status: "PLANNING",
    tags: ["design-system", "ui-ux", "aesthetics", "css"],
    technologies: [],
    title: "Bleverse Kitchen",
    ver: "",
    whoUses: ["cli"],
  },
  {
    category: "template",
    description: "conceptual universe building framework",
    docs: "https://docs.reliverse.org/bleverse",
    features: ["Universe Modeling", "Relationship Mapping", "Content Generation"],
    icon: "🌌",
    id: "bleverse",
    link: "https://github.com/blefnk/bleverse",
    longDescription:
      "An ambitious project aiming to create a framework or set of tools for building conceptual or fictional universes.",
    oss: false,
    relatedProjects: ["blenom", "bleways"],
    screenshots: ["/og-image.png"],
    soon: false,
    status: "ACTIVE",
    tags: ["world-building", "universe", "conceptual-design", "framework"],
    technologies: [],
    title: "Bleverse Framework",
    ver: "",
    whoUses: ["cli"],
  },
  {
    category: "template",
    description: "pathways, principles, and methodologies",
    docs: "https://docs.reliverse.org/bleways",
    features: ["Workflow Documentation", "Best Practices", "Guiding Principles"],
    icon: "🧭",
    id: "bleways",
    link: "https://github.com/blefnk/bleways",
    longDescription:
      "A collection documenting personal or project-specific pathways, guiding principles, and development methodologies.",
    oss: false,
    relatedProjects: ["bleverse", "blooks"],
    screenshots: ["/og-image.png"],
    soon: false,
    status: "PLANNING",
    tags: ["methodology", "principles", "workflow", "docs"],
    technologies: ["Fumadocs"],
    title: "Bleways Methodologies",
    ver: "",
    whoUses: ["cli"],
  },
  {
    category: "template",
    description: "digital book-like content creation tools",
    docs: "https://docs.reliverse.org/blooks",
    features: ["Book-like Structure", "Content Formatting", "Export Options"],
    icon: "📖",
    id: "blooks",
    link: "https://github.com/blefnk/blooks",
    longDescription:
      "Tools or a system designed for creating and formatting digital content in a book-like structure or appearance.",
    oss: true,
    relatedProjects: ["bleways", "bse"],
    screenshots: ["/og-image.png"],
    soon: false,
    status: "PLANNING",
    tags: [
      "books",
      "content",
      "digital-publishing",
      "digital",
      "tools",
      "content-creation",
      "formatting",
    ],
    technologies: [],
    title: "Blooks Content Tools",
    ver: "",
    whoUses: ["cli"],
  },
  {
    category: "template",
    description: "custom search engine with blefnk design principles",
    docs: "https://docs.reliverse.org/bse",
    features: ["Custom Search Algorithm", "Blefnk Design Integration", "Result Ranking"],
    icon: "🔍",
    id: "bse",
    link: "https://github.com/blefnk/bse",
    longDescription:
      "A custom search engine implementation, incorporating design principles or aesthetics from the 'blefnk' namespace.",
    oss: false,
    relatedProjects: ["blooks", "cfg"],
    screenshots: ["/og-image.png"],
    soon: false,
    status: "ACTIVE",
    tags: ["search-engine", "engine", "custom", "design", "indexing", "crawling"],
    technologies: [],
    title: "BSE Search Engine",
    ver: "",
    whoUses: ["cli"],
  },
  {
    category: "template",
    description: "personal configuration experiments and templates",
    docs: "https://docs.reliverse.org/cfg",
    features: ["Dotfile Management", "Environment Setup", "Tool Configuration"],
    icon: "⚙️",
    id: "cfg",
    link: "https://github.com/blefnk/cfg",
    longDescription:
      "A repository containing personal configuration files (dotfiles), setup scripts, and templates for various tools and environments.",
    oss: true,
    relatedProjects: ["bse", "mfp"],
    screenshots: ["/og-image.png"],
    soon: false,
    status: "ACTIVE",
    tags: ["config", "dotfiles", "personal", "template", "configuration", "shell", "scripting"],
    technologies: [],
    title: "CFG Configurations",
    ver: "",
    whoUses: ["cli"],
  },
  {
    category: "template",
    description: "mystery field project - experimental concept",
    docs: "https://docs.reliverse.org/mfp",
    features: ["Novel Concept Exploration", "Rapid Prototyping"],
    icon: "🎹",
    id: "mfp",
    link: "https://github.com/blefnk/mfp",
    longDescription: "Learn How to Play Piano on MFPiano Official Website",
    oss: false,
    relatedProjects: ["cfg", "relios"],
    screenshots: ["/og-image.png"],
    soon: false,
    status: "PLANNING",
    tags: ["music", "experimental", "prototyping", "mystery"],
    technologies: [],
    title: "MFPiano Official Website",
    ver: "",
    whoUses: ["cli"],
  },
  {
    category: "template",
    description: "vision for reliverse-based operating system",
    docs: "https://docs.reliverse.org/relios",
    features: ["Conceptual Design", "Architectural Planning", "Vision Document"],
    icon: "💻",
    id: "relios",
    link: "https://github.com/blefnk/relios",
    longDescription:
      "A conceptual project outlining the vision and potential architecture for an operating system built upon or inspired by the Reliverse ecosystem.",
    oss: true,
    relatedProjects: ["mfp", "uitm"],
    screenshots: ["/og-image.png"],
    soon: true,
    status: "PLANNING",
    tags: ["operating-system", "concept", "vision", "planning", "architecture"],
    technologies: ["ReliverseSDK"],
    title: "Relios OS Vision",
    ver: "",
    whoUses: ["cli"],
  },
  {
    category: "template",
    description: "transforming abstract ideas into tangible materials",
    docs: "https://docs.reliverse.org/uitm",
    features: ["Idea Capture", "Concept Development", "Materialization Workflow"],
    icon: "💡",
    id: "uitm",
    link: "https://github.com/blefnk/uitm",
    longDescription: "A project that I am developing for my university.",
    oss: true,
    relatedProjects: [],
    screenshots: ["/og-image.png"],
    soon: false,
    status: "PLANNING",
    tags: [
      "idea",
      "concept",
      "tangible",
      "process",
      "transformation",
      "ideation",
      "prototyping",
      "implementation",
    ],
    technologies: [],
    title: "UITM",
    ver: "",
    whoUses: ["cli"],
  },

  {
    category: "cli",
    description: "website builder CLI tool",
    docs: "https://docs.reliverse.org/cli",
    features: [
      "Project scaffolding",
      "Built-in development server",
      "Optimized build process",
      "One-command deployment",
      "Plugin system",
      "Template management",
    ],
    icon: "🧰",
    id: "cli",
    link: "https://github.com/reliverse/cli-website-builder",
    longDescription:
      "A command-line interface tool for rapidly building and deploying websites. Reliverse CLI streamlines the development workflow with automated tasks, templates, and deployment integrations.",
    oss: true,
    relatedProjects: ["reliverse"],
    screenshots: ["/reliverse.png"],
    soon: false,
    status: "ACTIVE",
    tags: ["cli", "website-builder", "scaffolding", "deployment", "bootstrapping", "build-tools"],
    technologies: ["Node.js", "ReliverseSDK"],
    title: "Reliverse CLI",
    ver: "",
    whoUses: ["cli"],
  },
  {
    category: "cli",
    description: "commit message formatting and enhancement tool",
    docs: "https://docs.reliverse.org/recme",
    features: ["Commit Formatting", "Convention Enforcement", "Emoji Support"],
    icon: "💬",
    id: "recme",
    link: "https://github.com/reliverse/recme",
    longDescription:
      "A CLI tool to help format Git commit messages according to conventions (e.g., Conventional Commits) and potentially enhance them with additional info.",
    oss: true,
    relatedProjects: ["cli", "reget"],
    screenshots: ["/og-image.png"],
    soon: false,
    status: "ACTIVE",
    tags: ["commit", "cli", "formatter", "conventional-commits"],
    technologies: ["Git", "Node.js"],
    title: "Recme Commit Enhancer",
    ver: "",
    whoUses: ["cli"],
  },
  {
    category: "cli",
    description: "template and project fetching utility",
    docs: "https://docs.reliverse.org/reget",
    features: ["Fetch Templates", "Project Initialization", "Repository Cloning"],
    icon: "📥",
    id: "reget",
    link: "https://github.com/reliverse/reget",
    longDescription:
      "A command-line utility, related to 'religet', for fetching project templates or boilerplate code from repositories.",
    oss: true,
    relatedProjects: ["recme", "reinct"],
    screenshots: ["/og-image.png"],
    soon: false,
    status: "ACTIVE",
    tags: ["cli", "fetch", "template", "scaffold", "scaffolding", "templates"],
    technologies: ["Git", "Node.js"],
    title: "Reget Fetch Utility",
    ver: "",
    whoUses: ["cli"],
  },
  {
    category: "cli",
    description: "initialization script wrapper and manager",
    docs: "https://docs.reliverse.org/reinct",
    features: ["Script Execution", "Configuration Management", "Setup Automation"],
    icon: "🚀",
    id: "reinct",
    link: "https://github.com/reliverse/reinct",
    longDescription:
      "A CLI tool that acts as a wrapper or manager for running various initialization scripts, potentially standardizing project setup.",
    oss: true,
    relatedProjects: ["reget", "reinit"],
    screenshots: ["/og-image.png"],
    soon: false,
    status: "ACTIVE",
    tags: ["cli", "init", "script", "wrapper", "automation", "scripting", "initialization"],
    technologies: ["Node.js", "TypeScript"],
    title: "Reinct Init Wrapper",
    ver: "",
    whoUses: ["cli"],
  },
  {
    category: "cli",
    description: "project bootstrapping and initialization tool",
    docs: "https://docs.reliverse.org/reinit",
    features: ["Project Setup", "Template Integration", "Configuration Wizard"],
    icon: "✨",
    id: "reinit",
    link: "https://github.com/reliverse/reinit",
    longDescription:
      "A command-line tool focused on bootstrapping new projects, setting up initial files, configurations, and dependencies.",
    oss: true,
    relatedProjects: ["reinct", "hub"],
    screenshots: ["/og-image.png"],
    soon: false,
    status: "ACTIVE",
    tags: ["cli", "init", "bootstrapping", "scaffold", "project-setup", "scaffolding"],
    technologies: ["Node.js", "TypeScript"],
    title: "Reinit Bootstrapper",
    ver: "",
    whoUses: ["cli"],
  },

  {
    category: "saas",
    description: "central native hub for all reliverse tools and resources",
    docs: "https://docs.reliverse.org/hub",
    features: [
      "Tool Discovery",
      "Resource Aggregation",
      "Documentation Access",
      "Unified Interface",
    ],
    icon: "🪐",
    id: "hub",
    link: "https://github.com/blefnk/hub",
    longDescription:
      "A central platform or application intended to consolidate access to various tools, docs, and resources within the Reliverse ecosystem.",
    oss: true,
    relatedProjects: ["reinit", "reliverse"],
    screenshots: ["/og-image.png"],
    soon: false,
    status: "ACTIVE",
    tags: ["platform", "hub", "ecosystem", "saas", "integration"],
    technologies: ["ReliverseSDK", "Next.js", "TypeScript"],
    title: "Reliverse Hub",
    ver: "",
    whoUses: ["cli"],
  },
  {
    category: "saas",
    description: "meta-repository for reliverse ecosystem coordination",
    docs: "https://docs.reliverse.org/ai",
    features: [
      "Overall Roadmap",
      "Community Discussion",
      "Contribution Guidelines",
      "Ecosystem Overview",
    ],
    icon: "⭐",
    id: "reliverse",
    link: "https://reliverse.org",
    longDescription:
      "The main meta-repository for the Reliverse project, containing overall documentation, issue tracking, and coordination efforts for the ecosystem.",
    oss: true,
    relatedProjects: ["hub", "blengine"],
    screenshots: ["/reliverse.png"],
    soon: false,
    status: "ACTIVE",
    tags: ["meta", "ecosystem", "coordination", "docs"],
    technologies: ["Fumadocs", "Github", "ReliverseSDK"],
    title: "Reliverse AI",
    ver: "",
    whoUses: ["cli"],
  },

  {
    category: "library",
    description: "rust-based 3d and game engine",
    docs: "https://docs.reliverse.org/blengine",
    features: ["Rust Core", "3D Rendering Pipeline", "Entity Component System (ECS)"],
    icon: "🎮",
    id: "blengine",
    link: "https://github.com/reliverse/blengine",
    longDescription:
      "A game and 3D rendering engine being developed using the Rust programming language, focusing on performance and safety.",
    oss: true,
    relatedProjects: ["reliverse", "rengine"],
    screenshots: ["/og-image.png"],
    soon: false,
    status: "PLANNING",
    tags: ["game-engine", "3d-graphics", "graphics", "rendering"],
    technologies: ["Rust"],
    title: "Blengine Game Engine (Rust)",
    ver: "",
    whoUses: ["cli"],
  },
  {
    category: "library",
    description: "typescript-based 3d and game engine",
    docs: "https://docs.reliverse.org/rengine",
    features: ["TypeScript Core", "WebGL Renderer", "Scene Management"],
    icon: "🕹️",
    id: "rengine",
    link: "https://github.com/reliverse/rengine",
    longDescription:
      "A game and 3D rendering engine built using TypeScript, potentially targeting web platforms (e.g., WebGL) or Node.js environments.",
    oss: true,
    relatedProjects: ["blengine", "rentime"],
    screenshots: ["/og-image.png"],
    soon: false,
    status: "PLANNING",
    tags: ["game-engine", "3d-graphics", "webgl", "graphics"],
    technologies: ["TypeScript"],
    title: "Rengine Game Engine (TS)",
    ver: "",
    whoUses: ["cli"],
  },
  {
    category: "library",
    description: "runtime environment for applications and games",
    docs: "https://docs.reliverse.org/rentime",
    features: ["Application Loading", "Resource Management", "API Abstraction"],
    icon: "⚙️",
    id: "rentime",
    link: "https://github.com/reliverse/rentime",
    longDescription:
      "A specific runtime environment designed to execute applications or games, possibly integrating with the Rengine or Blengine.",
    oss: true,
    relatedProjects: ["rengine", "relivator"],
    screenshots: ["/og-image.png"],
    soon: false,
    status: "ACTIVE",
    tags: ["runtime", "engine", "execution", "application", "games", "execution-environment"],
    technologies: ["TypeScript", "WASM"],
    title: "Rentime Runtime Environment",
    ver: "",
    whoUses: ["cli"],
  },

  {
    category: "template",
    description: "Next.js starter with Polar and Better Auth integration",
    docs: "https://docs.reliverse.org/relivator",
    features: [
      "Modern authentication with Polar and Better-Auth",
      "Type-safe API routes and database access",
      "Responsive design with Tailwind CSS",
      "Dark mode support",
      "SEO optimization",
      "Performance-focused architecture",
    ],
    icon: "✨",
    id: "relivator",
    link: "https://github.com/blefnk/relivator",
    longDescription:
      "A comprehensive Next.js template focused on developer experience and modern authentication patterns. Built to eliminate boilerplate and accelerate project development with a focus on clean DX and honest UX.",
    oss: true,
    relatedProjects: ["rentime", "versator"],
    screenshots: ["/og-image.png"],
    soon: false,
    status: "ACTIVE",
    tags: ["template", "starter", "auth", "tailwind-css"],
    technologies: ["Next.js", "TypeScript", "Polar", "Better-Auth", "Tailwind CSS"],
    title: "Relivator",
    ver: "",
    whoUses: ["cli"],
  },
  {
    category: "template",
    description: "next.js starter with stripe and clerk integration",
    docs: "https://docs.reliverse.org/versator",
    features: [
      "Integrated Stripe payment processing",
      "User authentication with Clerk",
      "Subscription management",
      "Dashboard for users and admins",
      "Email notifications",
      "Analytics integration",
    ],
    icon: "🚀",
    id: "versator",
    link: "https://github.com/blefnk/versator",
    longDescription:
      "A production-ready template for SaaS applications with integrated payment processing and authentication. Designed for rapid deployment of commercial web applications with a focus on monetization and user management.",
    oss: true,
    relatedProjects: ["relivator"],
    screenshots: ["/og-image.png"],
    soon: false,
    status: "ACTIVE",
    tags: ["template", "starter", "saas", "tailwind-css"],
    technologies: ["Next.js", "TypeScript", "Stripe", "Clerk", "Tailwind CSS"],
    title: "Versator",
    ver: "",
    whoUses: ["cli"],
  },
];
